# Generated by Django 4.2.3 on 2025-03-19 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('livability_score', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='city_images')),
            ],
        ),
        migrations.CreateModel(
            name='LivabilityFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livability.city')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livability.livabilityfactor')),
            ],
        ),
    ]
