# Generated by Django 4.2.3 on 2025-05-11 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livability', '0002_categoryfuzzycomparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='categoryfuzzycomparison',
            name='category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzzy_comp_1', to='livability.category'),
        ),
        migrations.AlterField(
            model_name='categoryfuzzycomparison',
            name='category2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzzy_comp_2', to='livability.category'),
        ),
        migrations.AlterField(
            model_name='citylivabilityscore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livability.category'),
        ),
        migrations.CreateModel(
            name='FuzzyWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_l', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight_u', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livability.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuzzy Weight',
                'verbose_name_plural': 'Fuzzy Weights',
                'unique_together': {('category', 'user')},
            },
        ),
    ]
